[theme]
# --- Perusteema ---
base = "light"

# --- Värit ---
primaryColor = "#00897B"              # hieman kirkkaampi teal
backgroundColor = "#F3FAF9"           # neutraali vaalea tausta
secondaryBackgroundColor = "#DFF0EE"  # laatikoiden tausta hieman tummempi kontrastiin
textColor = "#001F1B"                 # syvempi tummanvihreä teksti, parempi luettavuus

# --- Typografia ---
font = "sans serif"

# --- Korostusvärit ---
[theme.color]
successColor = "#00796B"
warningColor = "#FFA726"
errorColor = "#D32F2F"
