[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
base="light"
primaryColor="#009688"
backgroundColor="#F6F9F8"
secondaryBackgroundColor="#E0F2F1"
textColor="#003333"
font="sans serif"
