[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
base="light"
primaryColor="#009688"
backgroundColor="#0E1117"
secondaryBackgroundColor="#1E2A25"
textColor="#E0F2F1"
font="sans serif"
